### ISSUE TITLE
Firefox ESR exclude

### ISSUE THREAD

**Issue by BamaStangGuy** [xPaw/CF-ABetterBrowser#78]
We have many users who at work simply do not have a choice it what browser version they are using. Firefox has ESR which I believe should be excluded. While it may not have the latest features it is still a supported and secured browser. Currently there is no way to exclude an ESR release from detection. Current Firefox ESR releas eis 45.7.

**Comment by TeffenEllis** [comment]
I think we can get this live by end the me the week ☺️

**Comment by TeffenEllis** [comment]
Hi @BamaStangGuy,

I apologize for the delayed response. Upon further planning, the team has decided to not implement this feature. Firefox's ESR program does ensure more security support, but may not include features  required by the site owner. Additionally due to the versioned nature of this library, ESR releases can eventually fall out of support. 

Thank you for your request and for using Cloudflare Apps. 

Cheers,
Teffen
